VAGRANTFILE_API_VERSION='2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'precise64_cloudimg'
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'manifests'
    puppet.manifest_file = 'graphite.pp'
  end

  config.vm.provision :shell, path: 'setup_graphite.sh', privileged: false
  config.vm.network 'forwarded_port', guest: 80, host: 8080, auto_correct: true
  config.ssh.forward_agent = true
end
