VAGRANTFILE_API_VERSION='2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'precise64_cloudimg'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box'
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'manifests'
    puppet.manifest_file = 'graphite.pp'
  end

  config.vm.provision :shell, path: 'setup_graphite.sh', privileged: false
  config.vm.network 'forwarded_port', guest: 80, host: 8080, auto_correct: true
  config.vm.network 'forwarded_port', guest:8080, host:8081, auto_correct: true
  config.ssh.forward_agent = true
  config.vm.synced_folder "../carbon_cassandra_plugin/", "/vagrant/src/carbon_cassandra_plugin"
  config.vm.synced_folder "../graphite_cassandra_plugin/", "/vagrant/src/graphite_cassandra_plugin"
  config.vm.synced_folder "../graphite_ceres_plugin/", "/vagrant/src/graphite_ceres_plugin"
  config.vm.synced_folder "../../carbon/", "/vagrant/src/carbon"
end
